version: 2
updates:
- package-ecosystem: gradle
  directory: "/./ApiDemos/java"
  schedule:
    interval: weekly
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.android.tools.build:gradle
    versions:
    - 4.1.2
  commit-message:
    prefix: chore(deps)
- package-ecosystem: gradle
  directory: "/./ApiDemos/kotlin"
  schedule:
    interval: weekly
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.jetbrains.kotlin:kotlin-stdlib-jdk7
    versions:
    - 1.4.21-2
    - 1.4.30
    - 1.4.31
    - 1.4.32
  - dependency-name: org.jetbrains.kotlin:kotlin-gradle-plugin
    versions:
    - 1.4.21-2
    - 1.4.30
    - 1.4.31
    - 1.4.32
  - dependency-name: com.android.tools.build:gradle
    versions:
    - 4.1.2
  commit-message:
    prefix: chore(deps)
- package-ecosystem: gradle
  directory: "/./WearOS"
  schedule:
    interval: weekly
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.android.tools.build:gradle
    versions:
    - 4.1.2
  commit-message:
    prefix: chore(deps)
- package-ecosystem: gradle
  directory: "/./tutorials/java/CurrentPlaceDetailsOnMap"
  schedule:
    interval: weekly
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.android.tools.build:gradle
    versions:
    - 4.1.2
  commit-message:
    prefix: chore(deps)
- package-ecosystem: gradle
  directory: "/./tutorials/kotlin/CurrentPlaceDetailsOnMap"
  schedule:
    interval: weekly
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.jetbrains.kotlin:kotlin-stdlib-jdk7
    versions:
    - 1.4.21-2
    - 1.4.30
    - 1.4.31
    - 1.4.32
  - dependency-name: org.jetbrains.kotlin:kotlin-gradle-plugin
    versions:
    - 1.4.21-2
    - 1.4.30
    - 1.4.31
    - 1.4.32
  - dependency-name: androidx.lifecycle:lifecycle-viewmodel-ktx
    versions:
    - 2.3.0
  - dependency-name: com.android.tools.build:gradle
    versions:
    - 4.1.2
  commit-message:
    prefix: chore(deps)
- package-ecosystem: gradle
  directory: "/./tutorials/java/MapWithMarker"
  schedule:
    interval: weekly
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.android.tools.build:gradle
    versions:
    - 4.1.2
  commit-message:
    prefix: chore(deps)
- package-ecosystem: gradle
  directory: "/./tutorials/kotlin/MapWithMarker"
  schedule:
    interval: weekly
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.jetbrains.kotlin:kotlin-stdlib-jdk7
    versions:
    - 1.4.21-2
    - 1.4.30
    - 1.4.31
    - 1.4.32
  - dependency-name: org.jetbrains.kotlin:kotlin-gradle-plugin
    versions:
    - 1.4.21-2
    - 1.4.30
    - 1.4.31
    - 1.4.32
  - dependency-name: com.android.tools.build:gradle
    versions:
    - 4.1.2
  commit-message:
    prefix: chore(deps)
- package-ecosystem: gradle
  directory: "/./tutorials/java/Polygons"
  schedule:
    interval: weekly
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.android.tools.build:gradle
    versions:
    - 4.1.2
  - dependency-name: junit:junit
    versions:
    - 4.13.1
  commit-message:
    prefix: chore(deps)
- package-ecosystem: gradle
  directory: "/./tutorials/kotlin/Polygons"
  schedule:
    interval: weekly
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.jetbrains.kotlin:kotlin-stdlib-jdk7
    versions:
    - 1.4.21-2
    - 1.4.30
    - 1.4.31
    - 1.4.32
  - dependency-name: org.jetbrains.kotlin:kotlin-gradle-plugin
    versions:
    - 1.4.21-2
    - 1.4.30
    - 1.4.31
    - 1.4.32
  - dependency-name: com.android.tools.build:gradle
    versions:
    - 4.1.2
  - dependency-name: junit:junit
    versions:
    - 4.13.1
  commit-message:
    prefix: chore(deps)
- package-ecosystem: gradle
  directory: "/./tutorials/java/StyledMap"
  schedule:
    interval: weekly
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.android.tools.build:gradle
    versions:
    - 4.1.2
  commit-message:
    prefix: chore(deps)
- package-ecosystem: gradle
  directory: "/./snippets"
  schedule:
    interval: weekly
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.jetbrains.kotlin:kotlin-stdlib
    versions:
    - 1.4.21-2
    - 1.4.30
    - 1.4.31
    - 1.4.32
  - dependency-name: org.jetbrains.kotlin:kotlin-gradle-plugin
    versions:
    - 1.4.21-2
    - 1.4.30
    - 1.4.31
    - 1.4.32
  - dependency-name: com.google.maps.android:android-maps-utils
    versions:
    - 2.2.0
    - 2.2.1
  - dependency-name: androidx.navigation:navigation-fragment
    versions:
    - 2.3.2
    - 2.3.3
    - 2.3.4
  - dependency-name: androidx.navigation:navigation-ui
    versions:
    - 2.3.2
    - 2.3.3
    - 2.3.4
  - dependency-name: com.android.tools.build:gradle
    versions:
    - 4.1.2
  - dependency-name: junit:junit
    versions:
    - 4.13.1
  commit-message:
    prefix: chore(deps)
